from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Mapping

import tomli_w

from harness_asset_manager.atomic_files import atomic_write_text
from harness_asset_manager.errors import MutationError

from .model import AgentDefinition, AgentParseError, AgentTarget

# Marker for harnesses whose format differs from the store's, so the file must be
# rendered rather than symlinked. TOML and Markdown both treat `#` as a comment.
GENERATED_MARKER = "harness-asset-manager:generated"


class AgentHarnessAdapter:
    """Owns one harness's agents directory.

    Two ownership models, because the harnesses genuinely differ:

    - **symlink** (Claude, Cursor, Antigravity, OpenCode) — the harness reads the same
      markdown+frontmatter the store holds, so ownership is a link into the store.
      `is_symlink()` plus a target inside the store is the whole test, and editing the
      store file updates every harness at once.
    - **marker** (Codex) — Codex needs TOML with different keys, so a symlinked `.md`
      would be meaningless. We render a real file whose first line carries
      GENERATED_MARKER. **No drift detection**: re-enabling overwrites local edits to a
      rendered file. Detecting otherwise means content hashes, which is exactly the
      layer this rebuild removed.
    """

    def __init__(self, target: AgentTarget, store_root: Path) -> None:
        self.target = target
        self.store_root = store_root.resolve()

    @property
    def renders(self) -> bool:
        return self.target.render_format != "markdown"

    def binding_path(self, slug: str) -> Path:
        suffix = ".toml" if self.renders else ".md"
        return self.target.output_dir / f"{slug}{suffix}"

    def owns(self, path: Path) -> bool:
        if self.renders:
            return _has_marker(path)
        if not path.is_symlink():
            return False
        try:
            resolved = path.resolve()
        except OSError:
            return False
        return self.store_root in resolved.parents

    def is_enabled(self, slug: str) -> bool:
        return self.owns(self.binding_path(slug))

    def is_dangling(self, slug: str) -> bool:
        if self.renders:
            return False
        link = self.binding_path(slug)
        return link.is_symlink() and not link.exists()

    def enable(self, agent: AgentDefinition) -> None:
        self._require_supported()
        path = self.binding_path(agent.slug)
        if self.renders:
            if path.exists() and not _has_marker(path):
                raise MutationError(
                    f"a file we do not manage exists at {path}; will not overwrite"
                )
            path.parent.mkdir(parents=True, exist_ok=True)
            atomic_write_text(path, render_codex_agent(agent), follow_symlinks=True)
            return

        target = agent.path.resolve()
        if path.is_symlink():
            if path.resolve() == target:
                return
            # A stale or dangling link of ours is safe to repoint; anything else is not.
            if self.owns(path) or not path.exists():
                path.unlink()
            else:
                raise MutationError(
                    f"symlink at {path} points to {path.resolve()}, not {target}"
                )
        elif path.exists():
            raise MutationError(f"real file exists at {path}; will not overwrite")
        path.parent.mkdir(parents=True, exist_ok=True)
        path.symlink_to(target)

    def disable(self, slug: str) -> None:
        self._require_supported()
        path = self.binding_path(slug)
        if not path.exists() and not path.is_symlink():
            return
        if self.renders:
            if not _has_marker(path):
                raise MutationError(
                    f"{path} was not generated by harness-asset-manager; will not delete it"
                )
            path.unlink()
            return
        if not path.is_symlink():
            raise MutationError(f"not a symlink at {path}; will not delete a real file")
        path.unlink()

    def unmanaged_paths(self) -> tuple[Path, ...]:
        """Files in this harness's agents dir that we do not own."""
        if not self.target.supports_agents or not self.target.output_dir.is_dir():
            return ()
        return tuple(
            path
            for path in sorted(self.target.output_dir.glob(self.target.file_glob))
            if not path.is_symlink() and not self.owns(path)
        )

    def orphaned_links(self) -> tuple[Path, ...]:
        """Our symlinks whose store file is gone.

        Left alone these are invisible — the agent is no longer in the store, so it has
        no inventory row to hang a binding off. Surfaced as issues instead.
        """
        if self.renders or not self.target.output_dir.is_dir():
            return ()
        return tuple(
            path
            for path in sorted(self.target.output_dir.glob(self.target.file_glob))
            if path.is_symlink() and not path.exists()
        )

    def _require_supported(self) -> None:
        if not self.target.supports_agents:
            raise MutationError(
                f"{self.target.label} does not support installable agents: "
                f"{self.target.unavailable_reason}",
                status=400,
            )


def codex_agent_name(slug: str) -> str:
    """Codex resolves an agent by its ``name`` field, not its filename.

    Their own example pairs ``pr-reviewer.toml`` with ``name = "pr_reviewer"``, so the
    slug's hyphens become underscores.
    """
    return slug.replace("-", "_")


def render_codex_agent(agent: AgentDefinition) -> str:
    """Render the store's markdown agent as a Codex TOML agent definition."""
    document: dict[str, object] = dict(agent.codex_extras)
    document["name"] = codex_agent_name(agent.slug)
    document["description"] = agent.description or agent.name
    document["developer_instructions"] = agent.prompt
    return (
        f"# {GENERATED_MARKER} — edits are overwritten when this agent is re-enabled\n"
        + tomli_w.dumps(document)
    )


@dataclass(frozen=True)
class CodexAgentDocument:
    """The modeled Codex fields plus TOML keys HAM must carry through adoption."""

    name: str
    description: str
    prompt: str
    extras: Mapping[str, object]


def parse_codex_agent(path: Path) -> CodexAgentDocument:
    """Read a Codex TOML agent without discarding unmodeled fields.

    The inverse of :func:`render_codex_agent`, so a Codex-authored agent can be
    adopted into the store's markdown format rather than shown as un-actionable.
    """
    import tomllib

    try:
        data = tomllib.loads(path.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError) as error:
        raise AgentParseError(f"invalid Codex agent TOML: {error}") from error
    if not isinstance(data, dict):
        raise AgentParseError("Codex agent TOML must be a table")
    name = str(data.get("name") or path.stem).strip()
    return CodexAgentDocument(
        name,
        str(data.get("description") or "").strip(),
        str(data.get("developer_instructions") or "").strip(),
        {
            key: value
            for key, value in data.items()
            if key not in {"name", "description", "developer_instructions"}
        },
    )


def _toml_str(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _toml_multiline(value: str) -> str:
    # A basic multi-line string; escape backslashes and any embedded delimiter.
    escaped = value.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    return f'"""\n{escaped}\n"""'


def _has_marker(path: Path) -> bool:
    if not path.is_file():
        return False
    try:
        with path.open("r", encoding="utf-8") as handle:
            return GENERATED_MARKER in handle.readline()
    except OSError:
        return False


# Lives here rather than in inventory.py: the reconcile service needs it too, and
# importing it from the inventory would make the two modules circular.
TargetResolver = Callable[[], tuple[tuple[AgentTarget, ...], dict[str, "AgentHarnessAdapter"]]]


__all__ = [
    "AgentHarnessAdapter",
    "CodexAgentDocument",
    "TargetResolver",
    "GENERATED_MARKER",
    "codex_agent_name",
    "parse_codex_agent",
    "render_codex_agent",
]
